title: Gobinda Garai
email: garai@math.cas.cz
description: ''Truth is much too complicated to allow anything but approximations.'' — John Louis Von Neumann
baseurl: ""
url: "https://ggcas.github.io"
theme: minima
